package entities;


public class Bank extends ResourceBuilding{
	
	// Placeholder bank building dimensions
	private static final int bank_Height = 4;
	private static final int bank_Width = 4;
	private static final int bank_BaseGenAmt = 100; // Base amount that banks will generate for the user

	// A modifier on how much gold is generated by banks, for possible research opportunity
	private static double bank_rateModifier = 0.0;
	
	public Bank(Player p) {
		super(p, bank_Height, bank_Width, Resource.GOLD, bank_BaseGenAmt);
	}
	
	public void setRateModifier(double newRate){
		bank_rateModifier = newRate;
	}
	
	public void generateResource() {
		super.getOwner().receiveGold(super.calculateBundleAmount(bank_rateModifier));
	}
}
